language: java
before_install:
  - chmod +x gradlew
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.gradle
script:
  - ./gradlew clean
  - ./gradlew test
  - ./gradlew bootJar -x test
deploy:
  provider: heroku
  api_key:
    secure: 8488c898-cdf7-4ada-8f56-9a58631293e7
  app: parkingsystem
  on:
    repo: BinLuIS/ParkingSystem
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
